### PR TITLE
Add Dutch (nl) translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by lah7** [comment]
Thank you! 🇳🇱 I'll keep the pull request open (like with :fr: #308) and will merge closer towards a beta release, as strings are still a work in progress.

:bulb: For completion, there's one more file you can translate - the launcher itself: `source/launchers/polychromatic.desktop` [(see step 6 on "Creating a new translation" for an example)](https://polychromatic.app/docs/translations/#performing-a-new-translation)

**Comment by Vistaus** [comment]
> Thank you!  I'll keep the pull request open (like with  #308) and will merge closer towards a beta release, as strings are still a work in progress.
> 

👍🏻 

>  For completion, there's one more file you can translate - the launcher itself: `source/launchers/polychromatic.desktop` [(see step 6 on "Creating a new translation" for an example)](https://polychromatic.app/docs/translations/#performing-a-new-translation)

Done! 🙂

**Comment by lah7** [comment]
A new release (v0.7.0) is coming up! 👏🏼  There should be no more string changes now.

I introduced a minor conflict in `.desktop` by commenting out some features that won't make it for this new release.

It seems there are some locale bugs, see: https://github.com/polychromatic/polychromatic/pull/308#issuecomment-880605839

**Comment by lah7** [comment]
A new release is imminent. I fixed the conflict and merged the translation so far. Thanks again!

**Pull request merged**
