### PR TITLE
Localization optimization

### PR DESCRIPTION
**Pull request by shinenelson**
It is possible to dynamically generate the binary `.mo` translations using the `msgfmt` tool from the `gettext` tools. This helps to do away with checking in binary files into the repository.

This change removes the compiled binaries from the repository and uses the `msgfmt` command in the installation script (`install/install.sh`) to dynamically compile the translations to the correct directories during installation. I've also changed the directory structure for the translation files : `locale/<locale code>/{LC_MESSAGES => }/<name of POT file>` since we don't use `rsync` to copy the compiled binaries to the installation directory anymore. The structure needs to be maintained only at the installation directory and not necessary in the repository. I think that makes more sense.

Also, this would require an update to the [wiki page for translation](https://github.com/polychromatic/polychromatic/wiki/How-to-translate-the-application) regarding the path for the translation `.po` files. I made the change and committed it locally, but I was unable to push the changes to the `upstream` repository. Could someone with write access to the repository please update the wiki page? (Or I could `push` my changes if I'm given access to the repository) 

Note : This is a pretty breakable change. I've tested successfully on debian-like systems. Please test this change on arch-like and suse-like systems during review before merging this change in.

### CODE REVIEW

**Comment by shinenelson** [comment]
Sure. No problem.

I'm not familiar with how `make` works. The maximum knowledge I have (self-taught) is the structure of Makefiles and how the rules are processed (which is also why I ignored the `Makefile` and worked on the `install/install.sh` script from the start). I didn't expect it to be used somewhere in the project.

Quick question : If we're using `make` anyway, why don't we just use that and not the `install/install.sh` script? What is the rationale behind having a `Makefile` **AND** a `install.sh` script?
Is it that we had the install script in the beginning and the Makefile came in later? 
IMHO, I think we should migrate the install script to the `Makefile` (most of it is already there). Only the dependency checks and this one (localization) are pending. I think `autoconf` should help in that regard.
Again, this is all from a person who doesn't have any hands-on experience. Maybe it's not so easy as it sounds.

Anyway, I too am going to try and see if I can figure some `make` things out. I'm going to try this over the weekend and see what we can make out of it. I'll experiment with this project. :wink:

**Comment by shinenelson** [comment]
> I've enabled editing of the wiki, so you can push your change.

I've hit a weird issue with respect to that. I'm able to make changes online from the github interface, but I'm unable to `push` my changes via `git`. I've raised this issue with Github support and am expecting a response regarding the same.

**Comment by lah7** [comment]
> If we're using make anyway, why don't we just use that and not the install/install.sh script?

Good idea. This could unify the packaging for Debian/Ubuntu too, since it's just been the LESS that needed compiling (command is inside `debian/rules`) and the MO files were already generated. Since the `makefile` will be used by humans and computers (packaging, e.g. [for Arch](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=polychromatic)).

I think your `autoconf` suggestion would definitely help here. :+1:

----

> What is the rationale behind having a Makefile AND a install.sh script? Is it that we had the install script in the beginning and the Makefile came in later?

`install.sh` did come first, but also this project in its early days didn't have anything to compile (CSS/JS/Python is all interpreted). So back then, it was easy to clone and run (providing dependencies were installed) with system-wide installation being optional.

There is a "Check for Updates" option in the Preferences that executed `update.sh` (then `install.sh`), but that was only for manual installs as a convenience. We don't have to worry about changing the UI there as there's an overhaul going on in the [unstable](https://github.com/polychromatic/polychromatic/tree/unstable) branch (Still WIP).

-----

> Anyway, I too am going to try and see if I can figure some make things out.

I'm not familiar with `make` neither. So, let's *`make`* it work for the better. :smile:

**Comment by z3ntu** [comment]
If you add some build system, please use meson but not autotools.

This file (`meson.build`) installs all data stuff, translation stuff is WIP
```meson
project('polychromatic')

python3 = import('python3')

install_data('polychromatic-controller', install_dir : get_option('bindir'))
install_data('polychromatic-tray-applet', install_dir : get_option('bindir'))
install_man('man/polychromatic-controller.1')
install_man('man/polychromatic-tray-applet.1')

install_subdir('data', install_dir : join_paths(get_option('datadir'), 'polychromatic'), strip_directory : true)
install_subdir('pylib', install_dir : join_paths(python3.sysconfig_path('platlib'), 'polychromatic'), strip_directory : true)
install_subdir('install/hicolor', install_dir : join_paths(get_option('datadir'), 'icons'))


install_data('install/polychromatic-controller.desktop', install_dir : join_paths(get_option('datadir'), 'share/applications'))
install_data('install/polychromatic-tray-applet.desktop', install_dir : join_paths(get_option('datadir'), 'share/applications'))
install_data('install/polychromatic-tray-applet.desktop', install_dir : join_paths(get_option('sysconfdir'), 'xdg/autostart'))
```

**Comment by shinenelson** [comment]
If we use `meson`, we could probably use it for manual builds from source, but for packaging purposes, we'd still have to maintain the `Makefile` because most packaging systems use `autotools`.

**Comment by z3ntu** [comment]
No, we can nuke the Makefile when I'm finished with the meson stuff. It replaces the Makefile. 
Also I now have css stuff working and translations are WIP: https://github.com/z3ntu/polychromatic/commit/a3bde20f258bf770cdaf1b6dfc1df28ffad35d9e - will continue on Sunday

**Comment by shinenelson** [comment]
Are you sure we can package the application for the different distributions using `meson`? I come from a Debian environment and I haven't heard of them using `meson` to package applications. You might know better since you're the maintainer for more than one distribution. I'm just saying that we shouldn't make hasty decisions that might hinder the build process for the distributions.

**Comment by z3ntu** [comment]
Using meson is fine. The packaging scripts just need a bit adaption.

**Comment by z3ntu** [comment]
Here's my take on meson build with css and translations working: https://github.com/z3ntu/polychromatic/compare/07411473c2...meson-unstable
It's based on the unstable branch as translations are saner there (only one file per language instead of multiple ones). `install.sh`, `Makefile` and `generate-pots.sh` is most likely broken in that branch.

**Comment by lah7** [comment]
Thank you @shinenelson for kickstarting the improvements to optimising locales 2 years back! :smiley: 

It's been a loooonng while, but since the last comment, the project is now a PyQt5 app, switched to `meson` (thanks @z3ntu!) and the scripts for creating and building locales have been updated as a result.

(At this time of writing - I just need to finish the job by loading translations into to `.ui` files at runtime :ok_hand: )

**Pull request closed without merging**
