### PR TITLE
Blackwidow Elite and Mamba Elite layouts

### PR DESCRIPTION
**Pull request by beranat**
Dear **Luke Horwell**, I congratulate you with migration to new codebase and would merge Mamba Elite Mouse and Blackwidow Elite layouts instead old [Blackwidow Elite and Mamba Elite support](#200).

### CODE REVIEW

**Comment by boorac** [comment]
I would just like to say I am looking forward for Black Widows support like it is New Year! @beranat thanks!

**Comment by lah7** [comment]
Thank you! I intended to notify 🔔  old pull requests once I migrated the en_US layout (I'll do that today) and pushed docs for guidance. I completed the new documentation for **device maps** a day or two ago but I haven't pushed it live --- until now: https://polychromatic.app/docs/devicemaps/ 🎆 

Don't worry about the failed unit test. I'm not sure why it failed when it should have succeeded. ✅  I'll investigate this. 

---

Good job on working on this without documentation :+1: Just 1 error:

In the editor, clicking the 3 media buttons shows the SVG is not grouped correctly:

Screenshot_20210211_142756

✋🏼  I'm going to work through the **en_US** layout and add other device maps today, so I'll apply your changes to a new graphic as a courtesy and attribute to you in Git.

BlackWidow Mamba looks different to BlackWidow Chroma. I'll update the frame/fonts to resemble your keyboard. 🖌️ 

---

Changes needed on **scan codes** - this isn't used right now. In future, it will map physical buttons to their LED position on the matrix. [(See details in this upcoming doc)](https://polychromatic.app/docs/devicemaps/#scan-code-json)

* [ ] `blackwidowelite.json` is a duplicate of `blackwidow_m_keys.json`.
  * Please delete duplicate file **or:**
  * keep file and check each scan code (see docs) if you have time.  183-187 (macro keys) can be deleted as unused. Numbers should be mostly the same.

* [ ] `mambaelite.json` can be deleted / marked `null` as it's only for keyboards/keypad inputs.

**Comment by beranat** [comment]
Dear **Luke Horwell**, I thank you for fast answer and feedback.

> Good job on working on this without documentation +1 Just 1 error:
> In the editor, clicking the 3 media buttons shows the SVG is not grouped correctly:
> Screenshot_20210211_142756

You will be surprised, but this is not or incorrect group in layout: 
s2
This is an accurate keyboard's behavior implementation.

**Comment by lah7** [comment]
> You will be surprised, but this is not incorrect group in layout - it is an accurate keyboard's behavior implementation:

That is surprising!

I've completed rebasing the keyboard SVG against a newer en_US graphic (8e1c90e) - fonts on keys have been improved. 

Screenshot_20210211_201438

For the observant, the borders for the media buttons became different opacity semicircles -- by accident -- it is some kind of SVG or renderer bug. I think this visually helps, as those split across buttons took me by surprise.

Screenshot_20210211_201926 Screenshot_20210211_202046

I'm ready to proceed by resolving conflicts I introduced and merge the mouse. As noted above, the **scan codes** section is an unused feature, so we don't need it yet. Let me know if you wish to [correct the scan code JSON](https://polychromatic.app/docs/devicemaps/#scan-code-json) or if I should go ahead and merge without this.

**Comment by beranat** [comment]
Dear _Hawkeye_ **Luke Horwell**, 
> For the observant, the borders for the media buttons became different opacity semicircles -- by accident -- it is some kind of SVG or renderer bug. 
> Screenshot_20210211_201926
I suppose the problem is in SVG's complicity (I use inkscape as editor) - I simplify the SVG manually (merge the paths and removes groups) - it should help.

About scancodes - Yes, I suppose to keep it is a good idea - it will be helpful for color schema migration between different keyboards.

**Comment by beranat** [comment]
The scancodes has been updated. I use a special values for items, that have no scancode:
- "LOGO" - Razer logo at bottom of keyboard
- "FN" - for RazerFn key

**Pull request closed without merging**
