### PR TITLE
Add translation for PL (Poland)

### PR DESCRIPTION
**Pull request by GSoftwareDevelopment**
96% has been translated. I will complete the missing 4% in the near future :)

### CODE REVIEW

**Comment by GSoftwareDevelopment** [comment]
I have come across a few problems:
- I do not know why, but the translation of the header of the device list, the main window 'polychromatic-controller' does not take place.
- The color list, despite its translation, also does not change, for example, Tasks->Apply to all, the colors remain in English.
- also no translation for the 'Open Controller' item of the system tray applet.

**Comment by lah7** [comment]
Thank you! Sorry for taking so long to respond.

> The color list, despite its translation, also does not change, for example, Tasks->Apply to all, the colors remain in English.

This one is a bit different. Colours are generated when the application is first opened. deleting `~/.config/polychromatic/colours.json` should generate them in Polish.

There is a [`backend_refactor`](https://github.com/polychromatic/polychromatic/tree/backend_refactor) branch that fixed some translation issues. Hopefully that includes the strings that you've spotted! It should be possible to switch to the `backend_refactor` branch and update the translation under the new code if you like. Otherwise, I'll merge this after I tidy up some loose ends with `backend_refactor` and get that merged into `master`.

**Comment by GSoftwareDevelopment** [comment]
> Thank you! Sorry for taking so long to respond.

Heh. As you can see, I'm also having a 'little' lapse in replying :)

> This one is a bit different. Colours are generated when the application is first opened. deleting ~/.config/polychromatic/colours.json should generate them in Polish.

Ok, so I understand that the colour list is generated by the frontend application itself based on the translation.

> I'll merge this after I tidy up some loose ends with backend_refactor and get that merged into master.

I don't know myself. Maybe let it be as you write in the last (in quoted) sentence. :)

Greetings and Thank you for a great programme :)

**Review by 7Adrian — APPROVED** [review]
Nice job!

But need to correct in one place, because there is grammar mistake.

**Comment by lah7** [comment]
Thank you both for translating and proofing!  🇵🇱

**Pull request merged**
