### PR TITLE
Add devicemap - Razer BlackWidow V3 (US)

### PR DESCRIPTION
**Pull request by pmdumuid**
I've created a device map for my make / model / language of keyboard from a copy of `blackwidow_elite_en_US.svg` after adjusting positions of keys and aspects of the keyboard.

### CODE REVIEW

**Review by lah7 — APPROVED** [review]
Thank you, looks good! 👍🏼 

Before merging, I just made two tweaks:

* Saved as plain SVG, to remove some attributes that Inkscape saves that we don't need.
* In the editor, the Razer logo appeared like a wonky upside down triangle, so I just tweaked the path so it's flush with the unit - from what I could tell from product pictures:

    Screenshot_20230803_195017

**Comment by pmdumuid** [comment]
Thanks Luke,

Sorry, I forgot to convert to plain SVG.

Happy with the triangle change, but the reason for it was that I wanted the UI to be consistent across lightable elements when editing.

In real-life, when for all the keys on the keyboard, when one is lit with a colour, only the character itself and the glow under the key becomes that color, and the key itself is still mostly black.  However in the UI, this is not the case, the key itself is shown as the color, and the character is black or white.  I think this difference between real-life and the app UI is good as it makes it easier to see the colored pattern properly, and extended the concept to the logo.

Sorry about forgetting to strip the SVG.

Pierre

**Comment by lah7** [comment]
No worries at all, just wanted to do the housekeeping before merging :)

Thanks for the reason - it was the _lopsided_ triangle that made me want to make a quick adjustment, but that did mean I just made things inconsistent with the other graphics. I think most Razer keyboards are like this regarding the key character and underglow (no translucent keycaps), so good to know you like how our editor lights them up!

I think I'll update the logo path to be like the other graphics later today. If your BlackWidow V3 is anything like my older BlackWidows, the Razer logo is on a glossy _not-quite-a-rectangle_.

**Comment by lah7** [comment]
All good, graphic updated:

Screenshot_20230804_214911 Screenshot_20230804_214908

**Pull request merged**
