### PR TITLE
Update Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by UM-Li**
- Corrected the alt-menu entries so that they work properly.
- Translated strings newly added since last time.

### CODE REVIEW

**Comment by UM-Li** [comment]
Oops I ran `scripts/create-locales.sh` to update `zh_CN.po`, but it seems other POT files were also somehow changed...  I'm not sure if this may break something; if necessary I'll reopen this PR.

**Review by lah7 — APPROVED** [review]
谢谢 (Thank you!)

No problem about the other POT/PO files. For cleanness, I've taken them out of this pull request (to only show `zh_CN.po` changes) and squashed your two commits into one. Here's a trick for next time:

    git add locale/zh_CN.po
    git commit -m "Update Simplified Chinese Translation"

**Comment by lah7** [comment]
In the application, do the translations appear as expected in your locale?

For me (in any other language), passing `--locale` shows partial translations. Not a fault from your work, I think this has something to do with the [recent update](https://github.com/polychromatic/polychromatic/releases/tag/v0.9.0) (PyQt5 → PyQt6). I'll do some investigation and either fix or update documentation.

**Comment by UM-Li** [comment]
Hi @lah7, some strings do not show their translation here either (mine is a fully zh_CN.UTF-8 environment).  For now all entries in `zh_CN.po` have been translated, so it does seem like something with the source code.  There are occurrences of this in both the controller and the tray app:

屏幕截图_20240504_194824
屏幕截图_20240504_194926
屏幕截图_20240504_195009
屏幕截图_20240504_195017

**Comment by lah7** [comment]
Thanks for the info! There were a few bugs with how translations were processed, which have been fixed. These were mainly regressions from the v0.9.0 release.

Would you be happy to pull the latest changes and check your translation? There will be new strings for the tray applet and CLI interfaces too.

After the translation is up-to-date, I'll look at publishing a new release.

**Comment by lah7** [comment]
Thanks, great job! 👍🏼 

I made some attempts locally to try and accommodate the wider characters using code, but I didn't feel satisfied with the result without impacting other languages (mostly it ends up too wide in `--help`). I can see the problem, as far as the code is concerned, it's seen as 3 _characters_, but the terminal renders them wider.
```
123
...
VID
序列号  
^^^
```

This is what I was experimenting with → 30efc7e23054a014315f8bd9185cf4a6c3b9b608. I am wondering about discontinuing the CLI interface in future, so we shouldn't spend too long on this.

For now, the simplest solution seems to be adding additional spaces at the end of the translated string for this affected area. What do you think?

```diff
#: polychromatic-cli:385 polychromatic-cli:388 polychromatic-cli:391
#: polychromatic/controller/devices.py:933
msgid "Custom Effects"
-msgstr "自定义灯效"
+msgstr "自定义灯效    "
```

image

**Comment by UM-Li** [comment]
Yes, tested in my environment too and this works 👍

**Pull request merged**
